### ISSUE TITLE
Fix problem where running migrations changes db ids from integer to bigint and back

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3668] opened 2022-06-22 01:40 UTC
Fix problem where running migrations changes db ids from integer to bigint and back

They should be bigint

The problem seems to be the difference between `rake db:drop db:create db:migrate` and `rake db:setup`

**Comment by andreLumor** [comment] 2022-07-01 17:30
Hi! Is this still happening? I couldn't reproduce the error.

**Comment by mussajoop** [comment] 2022-07-25 23:18
Hi, yes it's still happening. For me, for example, when I run `rake db:migrate` some ids change from bigint to integer

**Comment by compwron** [comment] 2022-07-26 20:25
The problem seems to be the difference between rake db:drop db:create db:migrate and rake db:setup :/

**Comment by johncarlocerna** [comment] 2022-10-27 15:11
This is a known bug that has been addressed in Rails: https://github.com/rails/rails/issues/45093
If you're having this issue locally, you have to drop your database locally and recreate it.

**Closed** 2023-07-28 20:21 UTC
Labels: Help Wanted
