### ISSUE TITLE
Volunteer shown as actively assigned to two supervisors after being re-assigned

### ISSUE THREAD

**Issue by cliftonmcintosh** [rubyforgood/casa#797] opened 2020-09-19 20:30 UTC
## Expected Behavior
When a volunteer has been unassigned from a supervisor, that volunteer's listing with that supervisor should have the text "Unassigned" in the "Assign" column even after that volunteer has been assigned to a new supervisor.

## Actual Behavior
When a volunteer has been unassigned from a supervisor and then the volunteer has been assigned to a new supervisor, the list of volunteers for the old supervisor has the "Unassign" button visible for the volunteer.

## Steps to reproduce

- Assign a volunteer to one supervisor.
- Unassign that volunteer from that supervisor.
- Assign the volunteer to a different supervisor.
- Visit both supervisors' edit pages and note that the "Unassign" button is now visible for that volunteer on both views even though the volunteer is only actively assigned to one of them. 

## Screenshots and data

In this example, Lincoln Huels was unassigned from Craig Blick and then assigned to Mrs. Jarrett Dicki. Note the "is_active" flag for Lincoln's records. However, Lincoln no longer has the "Unassigned" text in the listing of Craig Blick's volunteers.

Database records
```sql
casa_development=# select sv.id, v.display_name as "volunteer", s.display_name as "supervisor", s.id as "supervisor id", sv.is_active
casa_development-# from users v
casa_development-# join supervisor_volunteers sv
casa_development-# on v.id = sv.volunteer_id
casa_development-# join users s
casa_development-# on s.id = sv.supervisor_id
casa_development-# order by s.id, v.display_name;
 id |    volunteer     |     supervisor     | supervisor id | is_active 
----+------------------+--------------------+---------------+-----------
  2 | Lincoln Huels    | Mrs. Jarrett Dicki |           101 | t
  1 | Steven Ebert     | Mrs. Jarrett Dicki |           101 | t
  3 | Lincoln Huels    | Craig Blick        |           102 | f
  5 | Nelly Schuppe II | Craig Blick        |           102 | t
(4 rows)

```

![sv-db-records](https://user-images.githubusercontent.com/3824492/93688216-c1f8e800-fa89-11ea-802a-de9bc5fdbb1d.png)

Mrs. Jarrett  Dicki (supervisor 101), the volunteer's current supervisor, correctly has the "Unassign" button visible for Lincoln Huels
![supervisor-101-correctly-active](https://user-images.githubusercontent.com/3824492/93688215-bc030700-fa89-11ea-8655-d7211f77f932.png)

Craig Blick (supervisor 102), the volunteer's previous supervisor, **_incorrectly_** has the "Unassign" button visible for Lincoln Huels
![supervisor-102-incorrectly-active-volunteer](https://user-images.githubusercontent.com/3824492/93688208-b1e10880-fa89-11ea-9bdd-c9beeaaaa60c.png)

**Comment by cliftonmcintosh** [comment] 2020-09-19 20:32
I believe this was introduced with https://github.com/rubyforgood/casa/pull/765

**Comment by compwron** [comment] 2020-09-20 21:07
Oh noooo not again
Thank you for the github issue. This definitely needs fixing

**Comment by Zrrrpy** [comment] 2020-09-20 22:56
@cliftonmcintosh just wanted to express my gratitude for all the detail you provided in this issue – I didn't need to add anything! Thank you for making this clear and easy for a contributor to pick up.

**Comment by drborges** [comment] 2020-09-22 18:47
I'll give this one a try. Perfect PR description 👌🏼

**Comment by cliftonmcintosh** [comment] 2020-09-23 00:46
@drborges 

One thing to note is that the volunteers to supervisors relationship is many to one right now. It seems to me that if there are two records for a volunteer in the `supervisor_volunteers` table, one which connects the volunteer to an old supervisor and another which connects the volunteer to a new supervisor, then the relationship should be many to many.


https://github.com/rubyforgood/casa/blob/master/app/models/user.rb#L18-L24

But I could be wrong

**Comment by compwron** [comment] 2020-09-23 00:53
Correct, one volunteer can only be actively assigned to one supervisor at a time. We also need to keep a record of a volunteer having previously been assigned to different supervisor. Is that many-to-many? Kind of? Whatever works 😅

**Comment by drborges** [comment] 2020-09-23 13:06
Thanks for the info @cliftonmcintosh, @compwron, I see what the problem is. I'll be working on a fix and some specs to cover that scenario.

**Comment by drborges** [comment] 2020-09-23 16:57
@cliftonmcintosh, @compwron I believe the PR above addresses the issue. Let me know if there's anything there you'd like changed, I'm aiming to merge it at some point this afternoon.

**Closed** 2020-09-23 17:38 UTC
Labels: :zap: Power :zap:, Priority: High, Type: Bug
