### ISSUE TITLE
Do not show casa case prefix filter to volunteer

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1258] opened 2020-11-05 07:48 UTC
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer

**Description**
Do not show casa case prefix filter to volunteer, because they will only ever have 1 or 2 cases

**Screenshots of current behavior, if any**
<img width="827" alt="Screen Shot 2020-11-04 at 11 47 21 PM" src="https://user-images.githubusercontent.com/578159/98212245-27991a80-1ef8-11eb-9d2a-c8e165f73fa6.png">

**Comment by littleforest** [comment] 2020-11-05 17:15
@Zrrrpy is this a dup now of #1265 ?

**Comment by Zrrrpy** [comment] 2020-11-05 17:34
no but it was a duplicate of #1264 - I just closed it. (#1265 fixes this view for supervisors and admins) Thank you for the catch @littleforest!

**Closed** 2020-11-24 20:48 UTC
Labels: :play_or_pause_button: Frontend, :raised_hands: Volunteer, Help Wanted, Priority: High
