### ISSUE TITLE
Bug: Fix js null reference error

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4097] opened 2022-10-21 19:44 UTC
### Environment
all

### Description
Fix this reference error.

![image](https://user-images.githubusercontent.com/8918762/197276542-1080d9ac-8135-4983-b0c7-14eef0b9a5d6.png)
emailToggle should only be called if its corresponding html element is found

See https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets
See [`app/javascript/src/require_communication_preference.js`](https://github.com/rubyforgood/casa/blob/main/app/javascript/src/require_communication_preference.js)
See [a fix of a similar bug](https://github.com/rubyforgood/casa/pull/4037)

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by AlysonBasilio** [comment] 2022-10-22 14:32
Hey @FireLemons, could you assign this problem to me? I would like to work on it.

**Comment by AlysonBasilio** [comment] 2022-10-22 15:18
Actually, I couldn't reproduce the error. Looking at the code, I think it has already been fixed by @Thrillberg on https://github.com/rubyforgood/casa/commit/f45bb7f502a08332e391769fcee5a22aa1464e80, maybe you can close this issue 😄

**Closed** 2022-10-23 01:40 UTC
Labels: Type: Bug, Help Wanted, Good First Issue
