### ISSUE TITLE
Apply Supervisor/Admin "Other Duties" view for volunteers - Remove "Other Duties" from cases view for all users

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5174] opened 2023-09-01 02:38 UTC
## Impacted User Types
 - volunteers
 - Admins
 - Supervisors
 
## Environment
Web app

## Current Behavior
"Other Duties" appears in the "My Cases" tab for all users.  
<img width="1161" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/620a1f13-67a2-4d41-9bfa-6acac8ec53a2">

## Expected Behavior after changes
- Volunteers should still be able to only see their own "Other duties"
- Supervisors should still only see their volunteer's "Other duties"
- Admins should still be able to see everyone's "Other duties"
- For all users - We want to remove "Other Duties" from the "My Cases" tab
- For volunteers - Apply the same "Other Duties" view/tab used for Supervisors/Admins to the volunteer view
- For volunteers - Add the "+ New Duty" button to the separated "Other Duties" page (place to the left of "Other Duties" title"). Supervisors and admins do not need to be able to create a new duty. 
- For volunteers - Put the "Other Duties" tab under "Emancipation Checklist(s)" on the navbar for volunteers
<img width="1163" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/ee4777ad-00ff-46dd-95f2-ad32565ee972">
- Supervisors 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chahmedejaz** [comment] 2023-09-01 11:28
Hey @bcastillo32, I'd like to work on this issue. Can you please assign it to me? Thanks :)

**Comment by bcastillo32** [comment] 2023-09-01 18:57
> Hey @bcastillo32, I'd like to work on this issue. Can you please assign it to me? Thanks :)

All set!

**Comment by chahmedejaz** [comment] 2023-09-01 21:09
Hey @bcastillo32 - I just observed that we have the _Other Duties_ under _My Cases_ for Supervisors/Admins as well. Do you want it removed for them under _My Cases_ as well?

**Comment by bcastillo32** [comment] 2023-09-01 21:27
> Hey @bcastillo32 - I just observed that we have the _Other Duties_ under _My Cases_ for Supervisors/Admins as well. Do you want it removed for them under _My Cases_ as well?

yes you're right. That was an oversight on my part - Other duties should only show on the separate page and be removed from the cases page for all users. I will update the ticket

**Comment by chahmedejaz** [comment] 2023-09-01 22:03
@bcastillo32 - 

1. We can safely remove the _Other Duties_ from _Cases_ for supervisors and admin because it's breaking for them when they try creating a new duty
2. However, currently volunteers can only Add Duties from the _My Cases_ page
3. Other Duties page is the view-only page for duties
4. Please let me know how do we want to handle the point#2. Thanks.

**Comment by chahmedejaz** [comment] 2023-09-01 22:34
**Update:**
@bcastillo32  - The development work is complete as per the Expected Behavior of the issue. We can finalize the ticket once we get update on [this](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1703369354). Thanks.

**Comment by bcastillo32** [comment] 2023-09-01 23:25
> **Update:** @bcastillo32 - The development work is complete as per the Expected Behavior of the issue. We can finalize this once we get update on [this comment](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1703369354). Thanks.

Let's add the " + New Duty" button to the "Other Duties" page for all users - I think it makes most sense to enter the form from there.

**Comment by chahmedejaz** [comment] 2023-09-02 06:30
@bcastillo32 - These requirements are apparently going against the existing implementation. That's why I think before moving forward, we should discuss them as well:

### Existing Implementation
1.  Supervisors and Admins **Cannot** add new duties, even though they can see the button. Upon clicking they would see the unauthorized message
2. Supervisors can only view his volunteers' other duties on the separate Other Duties page
3. Admins can view all of the duties added by all volunteers
4. According to the 2nd and 3rd points, 1st point seems to be the bug. i.e. Supervisors are Admins should not be able to view the "Add New Duties" button
5. Only the Volunteers can successfully add new duty

### After the Issue's Fix

- Volunteers can only view their own other duties on the Other Duty Page
-

**Comment by chahmedejaz** [comment] 2023-09-02 06:50
@bcastillo32 - These requirements are apparently going against the existing implementation. That's why I think before moving forward, we should discuss them as well:

### Existing Implementation
1.  Supervisors and Admins **cannot** add new duties, even though they can see the button. Upon clicking they would see the unauthorized message
2. Supervisors can only view his volunteers' other duties on the Other Duties page
3. Admins can view all of the duties added by all volunteers
4. According to the 2nd and 3rd points, 1st point seems to be the bug. i.e. Supervisors are Admins should not be able to view the "Add New Duties" button
5. Only the Volunteers can successfully add new duty
6. Duties on Other Duty page are viewed as following:
7. ![image](https://github.com/rubyforgood/casa/assets/59338032/2a5f6862-845d-4ba2-811a-8b6b3c89abf5)
8. The highlighted link goes to the edit profile page for the volunteer only accessible by supervisors and admins.

### After the Issue's Fix

- Volunteers can only view their own duties on the Other Duty Page
- I believe according to the 8th point, we should now hide the profile link if the volunteer is viewing their own duties.

Please let me know how do you want me to handle the existing functionality with the new requirements i.e. Ability to add or edit other duties.  Please let me know if you have any follow-up questions. Thanks :)

**Comment by bcastillo32** [comment] 2023-09-03 21:50
> @bcastillo32 - These requirements are apparently going against the existing implementation. That's why I think before moving forward, we should discuss them as well:
> 
> ### Existing Implementation
> 1. Supervisors and Admins **cannot** add new duties, even though they can see the button. Upon clicking, they would see the unauthorized message
> 2. Supervisors can only view his volunteers'  duties on the Other Duties page
> 3. Admins can view all of the duties added by all volunteers
> 4. According to the 2nd and 3rd points, 1st point seems to be the bug. i.e. Supervisors and Admins should not be able to view the "Add New Duties" button
> 5. Only the Volunteers can successfully add new duty
> 6. Duties on Other Duties page are viewed as following:
> 7. ![image](https://user-images.githubusercontent.com/59338032/265185147-2a5f6862-845d-4ba2-811a-8b6b3c89abf5.png)
> 8. The highlighted link goes to the edit profile page for the volunteer only accessible by supervisors and admins.
> 
> ### After the Issue's Fix
> * Volunteers can only view their own duties on the Other Duty Page
> * I believe according to the 8th point, we should now hide the profile link if the volunteer is viewing their own duties.
> 
> Please let me know how we want to handle the existing functionality with [these requirements](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1703491999). Please let me know if you have any follow-up questions. Thanks :)

Hi there - sorry for the back and forth. I have updated the expected behavior - let me know if this helps.

**Comment by bcastillo32** [comment] 2023-09-03 22:00
> @bcastillo32 - These requirements are apparently going against the existing implementation. That's why I think before moving forward, we should discuss them as well:
> 
> ### Existing Implementation
> 1. Supervisors and Admins **cannot** add new duties, even though they can see the button. Upon clicking, they would see the unauthorized message
> 2. Supervisors can only view his volunteers'  duties on the Other Duties page
> 3. Admins can view all of the duties added by all volunteers
> 4. According to the 2nd and 3rd points, 1st point seems to be the bug. i.e. Supervisors and Admins should not be able to view the "Add New Duties" button
> 5. Only the Volunteers can successfully add new duty
> 6. Duties on Other Duties page are viewed as following:
> 7. ![image](https://user-images.githubusercontent.com/59338032/265185147-2a5f6862-845d-4ba2-811a-8b6b3c89abf5.png)
> 8. The highlighted link goes to the edit profile page for the volunteer only accessible by supervisors and admins.
> 
> ### After the Issue's Fix
> * Volunteers can only view their own duties on the Other Duty Page
> * I believe according to the 8th point, we should now hide the profile link if the volunteer is viewing their own duties.
> 
> Please let me know how we want to handle the existing functionality with [these requirements](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1703491999). Please let me know if you have any follow-up questions. Thanks :)

I see what you are saying - sorry for not being specific. I updated the expected behavior. I like your idea about the unnecessary link when a volunteer is viewing their own other duties. Let's hide it for volunteers.

**Comment by chahmedejaz** [comment] 2023-09-05 10:20
Hey @bcastillo32 - The development work has been completed. The PR is ready now :)
Please review the following video and let me know if I'm missing anything. Thanks. :)
[Uploading Screencast from 09-05-2023 02:36:30 PM.webm…]()

**Closed** 2023-09-10 03:51 UTC
