### ISSUE TITLE
casa_case can be deactivated

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1182] opened 2020-10-25 00:23 UTC
AS an **admin**,
I WANT to be able to deactivate a `casa_case`,
SO THAT `casa_cases` which are no longer active don't congest my view of active `casa_cases`, and so that I can easily identify which `casa_cases` my `casa_org` is no longer serving.

### How it works now
`casa_cases` can only be created or edited, they can not be deactivated.
<img width="1440" alt="Screen Shot 2020-10-24 at 5 13 03 PM" src="https://user-images.githubusercontent.com/62810851/97096230-dba7c500-161d-11eb-9278-0b95378e467b.png">

### How it should work instead
Admins should have the ability to deactivate a `casa_case` on the Edit Case page.

### Acceptance Criteria
- [ ] A button to "Deactivate CASA Case" appears on the Edit CASA Case page next to "Update CASA Case"
- [ ] Clicking on "Deactivate CASA Case" triggers a dialogue reading: _Deactivating a CASA Case will unassign any volunteers currently assigned to this case. Are you sure you'd like to continue?_ and two buttons: "Yes, deactivate" and "No, go back"
- [ ] Clicking "Yes, deactivate" deactivates `casa_case`
- [ ] Clicking "No, go back" closes dialogue box.
- [ ] Date of deactivation should display on deactivated `case_contacts`. See example below from a deactivated volunteer account:
<img width="1369" alt="Screen Shot 2020-10-24 at 5 23 51 PM" src="https://user-images.githubusercontent.com/62810851/97096222-c763c800-161d-11eb-9036-1c9ca85672b7.png">

**Comment by sarslanoglu** [comment] 2020-10-25 11:37
@Zrrrpy I can work on this one!

**Comment by RachelWyatt** [comment] 2020-10-25 14:57
@Zrrrpy @sarslanoglu is this a duplicate of #1132 ?

**Closed** 2020-10-26 00:52 UTC
Labels: :crown: Admin, Hacktoberfest, Help Wanted, Priority: Medium
