### ISSUE TITLE
Send case contacts reminder email to volunteer without supervisor

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2611] opened 2021-09-18 20:59 UTC
### Impacted User Types
 - volunteers

### Environment
all

### Current Behavior
When a volunteer without a supervisor is sent a case contacts reminder email, it fails because a supervisor is required in the cc

### Expected Behavior
Sen the email without the cc

see `app/mailers/volunteer_mailer.rb`

**Comment by compwron** [comment] 2021-09-21 01:20
Closing, this is a duplicate of https://github.com/rubyforgood/casa/issues/2590

**Closed by compwron** 2021-09-21 01:20 UTC
Labels: Type: Bug, Help Wanted, :email: Email
