### ISSUE TITLE
Case contact for multiple cases appears multiple times in supervisor's weekly email 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3125] opened 2022-01-18 04:39 UTC
## What type(s) of user does this feature affect?
 - supervisors

## Description
When a volunteer makes a case contact for more than one case, that case contact then appears twice in the supervisor's weekly email. 

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by littleforest** [comment] 2023-07-28 19:25
@compwron @bcastillo32 can we either close this or move to To Do?

**Comment by compwron** [comment] 2024-05-26 20:23
needs to write a test to prove the bug is absent (and fix the bug if the bug is present)

**Comment by elasticspoon** [comment] 2024-06-25 22:07
I'm gonna call this not a bug. This happen presently, however, the weekly email looks like this:

![Image](https://github.com/rubyforgood/casa/assets/14540596/532ade9d-884f-4ae9-9e9a-47bbeecf129d)

Basically it goes

- Volunteer1
  - Case 1
    - Most Recent Contact
  - Case 2
    - Most Recent Contact
  - Case 3
    - Most Recent Contact
- Volunteer2
  - Case 1
    - Most Recent Contact
  - Case 2
    - Most Recent Contact
  - Case 3
    - Most Recent Contact
- Volunteer3
  - etc...

I don't really see a way to demonstrate that this was a single case contact for multiple cases without reworking the entire email display (and the way contacts for multiple cases work frankly).

**Closed by elasticspoon** 2024-06-25 22:07 UTC
Labels: not-ready-to-build, Needs Validation
