### ISSUE TITLE
speed up page load of volunteers by admin

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1260] opened 2020-11-05 07:56 UTC
there's an n+1 query in here somewhere, fix it
https://casa-r4g-staging.herokuapp.com/volunteers

**Comment by notapatch** [comment] 2020-11-26 10:17
Is this a duplicate of https://github.com/rubyforgood/casa/issues/1324 ?

**Comment by littleforest** [comment] 2020-11-27 00:45
yes!

**Closed by littleforest** 2020-11-27 00:45 UTC
Labels: :chart_with_upwards_trend: Performance Improvement, Help Wanted, Priority: Medium
