### ISSUE TITLE
Back link on admin create new case contact page gets stuck and goes nowhere

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1772] opened 2021-02-22 08:40 UTC
### Impacted User Types
admins

### Environment
my local

### Current Behavior
1. log in as admin
1. go to a case contact like http://localhost:3000/casa_cases/213
1. click "new case contac"
1. click "Back" link

### Expected Behavior
Should go back to somewhere

**Comment by rpolley** [comment] 2021-02-23 00:15
Tried to reproduce this but wasn't able to. Do you have any more information about what you were doing before this happened?

**Comment by compwron** [comment] 2021-02-23 04:12
@rpolley here is a reproduction on QA. thanks for looking into this!! :) 
![casa-stuck](https://user-images.githubusercontent.com/578159/108801295-3f011f80-754a-11eb-94cc-ace140d14b79.gif)

**Comment by rpolley** [comment] 2021-02-23 17:33
@compwron it's a bit hard to see what's going on here, do you have anything in a higher resolution?

**Comment by rpolley** [comment] 2021-02-23 18:20
hmm, interesting, I tried the same workflow in QA and it seemed like it attempted to load the same page that it did successfully in development but instead it just spun for a while and then errored. I think this might be performance related since the page its loading tries to show details about every case contact that the current user has access to, which for admins is every one created for their organization, ever.

**Comment by rpolley** [comment] 2021-02-23 18:29
Looks like this also happens if you just browse directly to /case_contacts as an admin

**Comment by rpolley** [comment] 2021-02-23 18:32
workflow also works successfully in QA as an admin for org 2, which is much smaller.

**Comment by rpolley** [comment] 2021-02-23 19:06
Managed to reproduce on my machine, if I use the same db seed settings as QA the docker instance sits at 100% cpu for around 20 seconds before the page loads.

**Comment by rpolley** [comment] 2021-02-23 19:15
So I can see two ways of resolving this:

- Don't send admins to this page, send them somewhere else instead
- Make this page use less resources for very large numbers of case contacts, perhaps through some sort of server-side pagination

@compwron which do you think would be the better approach here?

**Comment by hairedfox** [comment] 2021-04-02 02:56
@compwron 
I think the problem is case_contacts index page is loaded with a lot of things, and there are a bunch of unoptimized queries here. So it took quite long to load this page. I'm about to fix this one.

**Comment by hairedfox** [comment] 2021-04-02 02:57
@compwron Just a sample :D
![image](https://user-images.githubusercontent.com/42526152/113375514-be7bdd00-9399-11eb-8478-576ec2552822.png)

**Comment by hairedfox** [comment] 2021-04-02 13:49
@compwron when you have time, please check my pull request :D 

And I think we should consider using pagination here 😅

**Comment by compwron** [comment] 2021-04-02 15:11
Yep pagination is good :)

**Closed** 2021-04-03 02:28 UTC
Labels: Type: Bug
