### ISSUE TITLE
supervisors can add/edit their own mobile number

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1786] opened 2021-02-26 00:27 UTC
Part of epic #1017, dependent on #1785

AS a **supervisor**,
I WANT to add/edit a mobile number in my profile,
SO THAT I can receive SMS notifications.

### How it works now
It doesn't! Currently, email is the only contact medium associated with user accounts.

### How it should work 
Supervisors should be able to add/edit their own mobile number under "Edit Profile".

**Comment by xihai01** [comment] 2022-04-04 02:45
@compwron is this issue a duplicate of #1787?

**Closed** 2022-04-22 19:56 UTC
Labels: :no_good_man: User Permissions, :iphone: SMS, codethechange
