### ISSUE TITLE
[bug] Volunteer view in Supervisor/Admin dashboard should not default to search results from previous sessions.

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#451] opened 2020-07-26 19:39 UTC
Part of epic #105

**What type of user is this for? [admin/supervisor/volunteer/all]**
supervisors and admins

**Where does/should this occur?**
Volunteer view in supervisor and admin dashboard.

**Current behavior**
The volunteer view in supervisor/admin dashboard defaults to display only search results from the last session.

**Intended behavior**
The volunteer view in supervisor/admin dashboard should default to display all volunteers assigned to supervisor – in alphabetical order – first, followed by other volunteers. 
For admins, it should display all active volunteers in alphabetical order, followed by all inactive volunteers in alphabetical order.

**Screenshots**
The volunteer view should not look like this at login.
![Screen Shot 2020-07-26 at 12 39 24 PM (2)](https://user-images.githubusercontent.com/62810851/88487860-b8e21380-cf3d-11ea-803f-82454754bdf7.png)

**Comment by cliftonmcintosh** [comment] 2020-07-26 23:24
Is there guidance on how to reproduce this? 

I have tried logging in as a supervisor, changing the filters, logging out and then back in. When I log back in, the filters I had set in the previous session are no longer there. They have been reset so that the logged-in supervisor sees only that supervisor's volunteers and sees all of them.

I've also tried filtering, closing a browser window without logging out, then opening a new window. In that scenario, the filters that I had set before are no longer there. As with the other scenario, they have been reset so that the logged-in supervisor sees only that supervisor's volunteers and sees all of them.

**Comment by cliftonmcintosh** [comment] 2020-07-26 23:26
NVM. I see now. It's the "search" box over on the right that affects the behavior. I didn't see that when experimenting earlier.

**Comment by cliftonmcintosh** [comment] 2020-07-27 13:43
This occurs because the search is cached in the browser's local storage. From what I can tell, this capability is driving by the [ jquery-datatables-rails](https://rubygems.org/gems/jquery-datatables-rails) gem. I have looked through the [README](https://github.com/rweng/jquery-datatables-rails) for that project, but I don't see information there on how to control this behavior.

Does anyone have any guidance on this? Neither looking through that project's issues nor Googling has yielded anything for me. I also took a look at an alternative gem, [jquery-datatables](https://github.com/mkhairi/jquery-datatables), and the [manual for the underlying jquery library](https://datatables.net/manual/index), but I haven't found anything there that might help.

Here is a screenshot showing a cached search for "Lucinda". Note that the user has logged out but the search cache has remained in browser's local storage. The cache also affects any other user who might log in from the same browser on the same computer. I don't know how often this scenario occurs.

![data-tables-in-local-storage](https://user-images.githubusercontent.com/3824492/88548294-89d2ad00-cfe4-11ea-9b59-5597d915eb36.png)

**Comment by compwron** [comment] 2020-07-27 15:20
Hmm, thanks for digging into this! I think a good solution for this would be to delete the DataTables part of localstorage on logout. 
https://developer.mozilla.org/en-US/docs/Web/API/Storage/removeItem
`localStorage.setItem("key", value);`
`localStorage.removeItem(keyName);`

**Comment by cliftonmcintosh** [comment] 2020-07-27 22:01
What are the options for adding a JavaScript function on logout?

Here is how the link is created:
https://github.com/rubyforgood/casa/blob/master/app/views/layouts/_header.html.erb#L24
https://github.com/rubyforgood/casa/blob/master/app/helpers/application_helper.rb#L12-L18

**Comment by compwron** [comment] 2020-07-27 22:28
I think that if we wanted to run js on logout, we might attach it to the click event of the logout link/button.

**Comment by bklang** [comment] 2020-08-01 16:59
Can I propose an alternative: What if we cleared all localStorage on login? This has a couple of advantages:
* It clears all potentially stale data, rather than just the DataTables values mentioned here, which protects against cached data format changes on login
* If a user loses their session for other reasons (for example, because they cleared cookies) the data will still be safely cleared
* (probably not a problem in this case) This approach also protects any user who logs out prior to this change being made

**Comment by cliftonmcintosh** [comment] 2020-08-01 19:09
I'm unlikely to work on this in the near term, so anyone else interested should please feel free to pick it up.

**Comment by alindeman** [comment] 2020-08-02 02:25
I gave this a go in #483. Feedback welcomed: JavaScript is not my primary language.

**Closed** 2020-08-02 18:06 UTC
Labels: :clipboard: Supervisor, :crown: Admin, Help Wanted, Priority: Medium
