### ISSUE TITLE
Sign In after previous Sign in and Sign Out leads "You are already signed in" message 

### ISSUE THREAD

**Issue by shankypr** [rubyforgood/casa#461] opened 2020-07-28 22:38 UTC
**What is the problem, and what should happen instead?**

1. Sign in as volunteer1@example.com
2. Sign out
3. Try same username for sign in 
4. Enter incorrect password or correct one

Expected: 

- if incorrect password entered, should get a message saying password is incorrect 
- if correct password is entered, should allow sign in to see cases

Actual: Takes you to another screen that says "You are already signed in" and shows a blank table under case count

  
<img width="1590" alt="Screen Shot 2020-07-28 at 3 22 39 PM" src="https://user-images.githubusercontent.com/962037/88729273-54af8300-d0e8-11ea-8dab-4ae426583b12.png">

**Comment by alindeman** [comment] 2020-08-08 19:43
I tried to reproduce this one, but wasn't able to. With the correct password, I was logged in (without any message about 'You are already signed in'); with the incorrect password, I was not signed in and received a message about the password being incorrect.

**Comment by Garbar** [comment] 2020-08-12 14:04
I was also unable to reproduce this error.

**Comment by compwron** [comment] 2020-08-12 15:22
Thanks for checking y'all! Since we can't reproduce it, I will close it.

**Closed by compwron** 2020-08-12 15:22 UTC
